### ISSUE TITLE
failed to compile in mac os10.11, fv_cached compilation failed

### ISSUE THREAD

**Issue by umichwanyi** [rbgirshick/voc-dpm#11]
When running your compile.m, I see this warning
Warning: Maybe you need to call fv_cache('unlock') first? 
> In fv_compile (line 52)
  In compile (line 48) 
which means I can not successfully compile fv_cache.cc function.
I saw your comment in this exception, but I don't know how to solve this problem.
There is one guy in stack overflow suggested that he has met the same problem, and he solve it by installing gcc48. 
http://stackoverflow.com/questions/24150718/voc-release-5-demo-m-is-not-working/33789824#33789824
Is that the correct way?

**Comment by ElaineJiang** [comment]
Any idea on how to fix this? I tried gcc48/gcc47/gcc46 but none of them works for Mac.
